name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Upgrade Poetry (if needed)
      run: |
        poetry self update

    - name: Cache Poetry dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies using Poetry
      run: |
        poetry install

    - name: Set version to 3.0.0
      run: |
        poetry version 3.0.0

    - name: Commit version change (if version changed)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add pyproject.toml
        git commit -m "Bump version to 3.0.0" || echo "No changes to commit"
        git push origin main

    - name: Clean previous builds (optional)
      run: |
        rm -rf dist/

    - name: Build the package
      run: |
        poetry build

    - name: Publish to PyPI
      env:
        POETRY_HTTP_BASIC_PYPI_USERNAME: __token__
        POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        poetry publish --build --no-interaction -vv
